---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  # The following is option and can be set as auto (which is warn by default),
  #   info, debug, or warn.
  #log_level: debug

platforms:
  - name: macos-10.12
    driver:
      synced_folders:
        - [".", "/vagrant", "owner: :vagrant, group: :wheel, create: true, type: :rsync"]
        - ["~/.kitchen/cache", "/tmp/omnibus/cache", "owner: :vagrant, group: :wheel, create: true, type: :rsync"]
      gui: true

verifier:
  name: inspec

suites:
  - name: plist_file
    run_list:
      - recipe[test::plist_file]
    verifier:
      inspec_tests:
        - test/integration/plist_file
    attributes:
  - name: userdefaults
    run_list:
      - recipe[test::userdefaults]
    verifier:
      inspec_tests:
        - test/integration/userdefaults
    attributes:

