---
driver:
  name: vagrant
  gui: false
  linked_clone: true
  synced_folders:
    - [".", "/vagrant", "owner: :vagrant, group: :wheel, create: true, type: :rsync"]
    - ["~/.kitchen/cache", "/tmp/omnibus/cache", "owner: :vagrant, group: :wheel, create: true, type: :rsync"]


provisioner:
  name: chef_solo
  #log_level: debug

platforms:
  - name: macos-10.12

verifier:
  name: inspec

suites:
  - name: plist_file
    run_list:
      - recipe[test::plist_file]
  - name: userdefaults
    run_list:
      - recipe[test::userdefaults]
